### ISSUE TITLE
Creating initial description on VCARD

### ISSUE THREAD

**Issue by wsdwl** [CalConnect/DEVGUIDE#19]

**Comment by ronaldtse** [comment]
Thanks @wsdwl for putting this up.

**Comment by ronaldtse** [comment]
@dthewlis , I've added an introduction to vCard with a brief history, which is obviously from stories you told me before 👍  Could you let me know if the description is accurate? Thanks!

**Comment by wsdwl** [comment]
Looks good to me and can be viewed on http://devguide.wsdwl.de/vCard/introduction

Next step would be to describe the Data Model e.g. like done for iCal:

http://devguide.calconnect.org/Data-Model/Data-Model
http://devguide.calconnect.org/Data-Model/Simple-Event

**Comment by dthewlis** [comment]
Hi Ron,

The history of vCARD 4 is a bit more complex.  Most importantly perhaps, RFC 6350 wasn’t an CalConnect effort, although most everything since then has been.  Here’s a quick potted history:

In the early days of CalConnect (i.e. 2006/2007), we talked a fair amount about whether we should also tackle a revision of vCard (which was then at 3.1, but 2.0 was still in general use).  At that point it wasn’t clear that vCARD was actually within our scope.  What we finally did was sponsor a workshop on vCard which was held during the CalConnect meeting at MIT in September 2007.  A fair number of interested parties who weren’t calendaring people or from CalConnect members came to the workshop; our point was that something needed to be done but CalConnect wasn’t prepared (in resources or possibly in scope) to undertake it.

The result of the workshop was that the IETF undertook a revision of vCard and assigned an editor; the result was vCard 4 which from our members’ point of view wasn’t a really satisfactory follow-on.  Possibly because of the effort to keep it compatible with vCard 3, few people seem to have felt it important to implement if they had vCard 3 implemented.  

Since then, very little work on vCard has happened within the IETF, and at this point it seems anything new will have to come from CalConnect, which long since has decided vCard is really inseparable from vCalendar as far as what we’re trying to do.  In particular we started to develop specifications especially in the area of resources which depended upon vCard 4, and did CardDAV as well.   

Dave




--
Dave Thewlis, Executive Director
CalConnect - The Calendaring and Scheduling Consortium
+1 707 840 9391 voice | +1 707 498 2238 mobile | +1 415 946 3454 fax
http://www.calconnect.org | Dave.Thewlis@calconnect.org

**Comment by ronaldtse** [comment]
Thank you Dave, I will update the text. With regards to the inheritance of intellectual property, was it accurate to say:

versit Corporation => IMC => CalConnect
or was it
versit Corporation => IMC => IETF => CalConnect?

**Comment by dthewlis** [comment]
I’m not sure how to adjust this. 

Versit Consortium to IMC is correct.  IMC to IETF is correct for VCALENDAR, but I believe IMC held onto VCARD for a while.  At one point IMC offered the IP to Calconnect (or rather the guy who had been running the IMC, which was out of business by the time we started), but we didn’t take him up on it as we don’t assert or own IP of our own.  

Note also that we tend to work on IETF stuff mostly, or within the IETF domain.  The IETF asserts copyright on their RFCs, we make anything we publish freely available under a Creative Commons license.   

Ultimately the IETF became the inheritor of VCARD as far as the IP goes, but has effectively passed the mantle of extending it on to us.

**Comment by ronaldtse** [comment]
@dthewlis I've updated the content as per your description. Closing this issue for now. Thanks!
