### ISSUE TITLE
How to integrate PlantUML in our CalConnect server?

### ISSUE THREAD

**Issue by wsdwl** [CalConnect/DEVGUIDE#26]
Ask Marten about how to do it?

**Comment by dmfs** [comment]
It's been a while since I did that. IIRC, the basic steps are:

* Create a new application with Tomcat 7
* Add a Graphviz cartridge from https://github.com/puzzle/openshift-graphviz-cartridge
* Add a plantuml cartridge from https://github.com/barnabycourt/openshift-plantuml-cartridge

Afterwards you need to adjust the plantuml URL in the Gollum config to point to the new application.

Note that you can't run it in the same application as the Gollum instance, because Gollum runs on Ruby and plantuml on Java.

**Comment by wsdwl** [comment]
Will try that until the next call in two weeks.

**Comment by wsdwl** [comment]
As openshift is shutting down our current used product, we will find a new solution and don't follow this path anymore.
