### ISSUE TITLE
Set up dev server 

### ISSUE THREAD

**Issue by douglm** [CalConnect/DEVGUIDE#7]
Useful to have a unpublished servic ethat reflects the current state of the repository and is updated automatically.
Allows editors to see the results of their changes before we publish to the public site

**Comment by wsdwl** [comment]
We still don't have an automated version of that, but
- there is a new url to try out things, which can be pushed from me, we are currently using at the interop to check with new content and layout issues -> http://devguide-wsdwl.rhcloud.com/Home
- since Monday Marten also added my ssh-keys to the rhcloud server, so I am able to push the content on the production site also

Unfortunately no new accounts can be created at rhcloud, so others are not able to d the same as I did too.

**Comment by wsdwl** [comment]
It's working for now and we have everything we can provide at the moment.
